"""Add idempotent payment and referral safeguards.

Revision ID: 20260728_01
Revises:
Create Date: 2026-07-28

The project historically created tables with ``Base.metadata.create_all``.
For a fresh database this bootstrap revision creates a *frozen* baseline
schema and records the revision.  It never imports live application models,
so a future Python-model edit cannot silently change a database during this
old migration. Existing installations receive only the additions below; no
business data is deleted or rewritten.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20260728_01"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PAYMENTS_TABLE = "payments"
REFERRALS_TABLE = "referral_transactions"
ACCOUNTS_TABLE = "accounts"
PAYMENT_PROVIDER_ID_UNIQUE = "uq_payment_method_payment_id"
REFERRAL_ORDER_UNIQUE = "uq_referral_order_referrer"
EXTERNAL_ORDER_INDEX = "ix_payments_external_order_id"
IDEMPOTENCY_KEY_INDEX = "ix_payments_idempotency_key"
ACCOUNT_ORDER_INDEX = "idx_account_order_id"
CORE_LEGACY_TABLES = {
    "users",
    "categories",
    "products",
    "orders",
    "accounts",
    "payments",
}


def _has_table(bind, table_name: str) -> bool:
    return table_name in sa.inspect(bind).get_table_names()


def _column_names(bind, table_name: str) -> set[str]:
    return {column["name"] for column in sa.inspect(bind).get_columns(table_name)}


def _has_unique_identity(bind, table_name: str, columns: list[str]) -> bool:
    """Return whether a unique constraint or unique index covers exactly columns."""
    inspector = sa.inspect(bind)
    expected = tuple(columns)

    for constraint in inspector.get_unique_constraints(table_name):
        if tuple(constraint.get("column_names") or ()) == expected:
            return True

    for index in inspector.get_indexes(table_name):
        if index.get("unique") and tuple(index.get("column_names") or ()) == expected:
            return True

    return False


def _index_by_name(bind, table_name: str, index_name: str):
    for index in sa.inspect(bind).get_indexes(table_name):
        if index.get("name") == index_name:
            return index
    return None


def _duplicate_group_count(bind, table_name: str, columns: list[str]) -> int:
    """Count duplicate non-NULL value groups without exposing payment values."""
    # All identifiers here are module constants, never request data.
    select_columns = ", ".join(columns)
    not_null = " AND ".join(f"{column} IS NOT NULL" for column in columns)
    result = bind.execute(
        sa.text(
            f"""
            SELECT COUNT(*)
            FROM (
                SELECT 1
                FROM {table_name}
                WHERE {not_null}
                GROUP BY {select_columns}
                HAVING COUNT(*) > 1
            ) AS duplicate_groups
            """
        )
    )
    return int(result.scalar_one())


def _require_no_duplicates(bind, table_name: str, columns: list[str], label: str) -> None:
    duplicate_groups = _duplicate_group_count(bind, table_name, columns)
    if duplicate_groups:
        column_list = ", ".join(columns)
        raise RuntimeError(
            f"Cannot add {label}: table '{table_name}' contains "
            f"{duplicate_groups} duplicate group(s) for ({column_list}). "
            "Resolve or merge those rows manually, then run 'alembic upgrade head' again. "
            "This migration has not deleted any data."
        )


def _ensure_unique_index(bind, table_name: str, index_name: str, columns: list[str]) -> None:
    if _has_unique_identity(bind, table_name, columns):
        return

    # A prior non-unique index with the name generated by SQLAlchemy must be
    # replaced; this changes only index metadata, never rows.
    existing_index = _index_by_name(bind, table_name, index_name)
    if existing_index is not None:
        op.drop_index(index_name, table_name=table_name)

    op.create_index(index_name, table_name, columns, unique=True)


def _ensure_index(bind, table_name: str, index_name: str, columns: list[str]) -> None:
    """Create a non-unique index once, without touching table data."""
    if _index_by_name(bind, table_name, index_name) is None:
        op.create_index(index_name, table_name, columns, unique=False)


def _ensure_unique_constraint(bind, table_name: str, constraint_name: str, columns: list[str]) -> None:
    if _has_unique_identity(bind, table_name, columns):
        return

    # Do not leave a same-named regular index in the way on PostgreSQL.
    existing_index = _index_by_name(bind, table_name, constraint_name)
    if existing_index is not None:
        op.drop_index(constraint_name, table_name=table_name)

    if bind.dialect.name == "sqlite":
        # SQLite cannot add a table-level UNIQUE constraint in place. Alembic's
        # batch operation copies all existing rows and preserves them.
        with op.batch_alter_table(table_name, recreate="always") as batch_op:
            batch_op.create_unique_constraint(constraint_name, columns)
    else:
        op.create_unique_constraint(constraint_name, table_name, columns)


def _validate_existing_data(bind) -> None:
    """Fail before DDL if existing values would violate a new uniqueness rule."""
    if _has_table(bind, PAYMENTS_TABLE):
        payment_columns = _column_names(bind, PAYMENTS_TABLE)
        required = {"payment_method", "payment_id"}
        if not required.issubset(payment_columns):
            raise RuntimeError(
                "Cannot migrate table 'payments': required columns "
                "payment_method and payment_id are missing. Restore a supported "
                "schema or migrate it manually before continuing."
            )
        _require_no_duplicates(
            bind,
            PAYMENTS_TABLE,
            ["payment_method", "payment_id"],
            "the payment provider/id uniqueness rule",
        )
        for column, label in (
            ("external_order_id", "the external_order_id unique index"),
            ("idempotency_key", "the idempotency_key unique index"),
        ):
            if column in payment_columns:
                _require_no_duplicates(bind, PAYMENTS_TABLE, [column], label)

    if _has_table(bind, REFERRALS_TABLE):
        referral_columns = _column_names(bind, REFERRALS_TABLE)
        required = {"order_id", "referrer_id"}
        if not required.issubset(referral_columns):
            raise RuntimeError(
                "Cannot migrate table 'referral_transactions': required columns "
                "order_id and referrer_id are missing. Restore a supported schema "
                "or migrate it manually before continuing."
            )
        _require_no_duplicates(
            bind,
            REFERRALS_TABLE,
            ["order_id", "referrer_id"],
            "the referral order/referrer uniqueness rule",
        )


def upgrade() -> None:
    bind = op.get_bind()
    existing_tables = set(sa.inspect(bind).get_table_names())
    has_users = "users" in existing_tables
    has_payments = PAYMENTS_TABLE in existing_tables

    # A fresh deployment is provisioned solely through Alembic.  The metadata
    # is a static snapshot of revision 20260728_01, not Base.metadata.
    if not has_users and not has_payments:
        # A dedicated new database may contain only Alembic's own table. Any
        # other application table means an interrupted/manual bootstrap and
        # must be reviewed rather than silently marked as migrated.
        unexpected = existing_tables - {"alembic_version"}
        if unexpected:
            names = ", ".join(sorted(unexpected))
            raise RuntimeError(
                "Cannot bootstrap a partially populated database. Found tables: "
                f"{names}. Restore a complete backup or finish the legacy "
                "schema manually before running Alembic."
            )
        from migrations.schema_20260728 import metadata

        metadata.create_all(bind=bind, checkfirst=True)
        return

    missing_core = CORE_LEGACY_TABLES - existing_tables
    if missing_core:
        names = ", ".join(sorted(missing_core))
        raise RuntimeError(
            "Cannot migrate a partial legacy Digital Networks schema; missing "
            f"core table(s): {names}. Restore a complete backup or repair the "
            "schema manually before running Alembic."
        )

    _validate_existing_data(bind)

    if _has_table(bind, PAYMENTS_TABLE):
        columns = _column_names(bind, PAYMENTS_TABLE)
        if "external_order_id" not in columns:
            op.add_column(
                PAYMENTS_TABLE,
                sa.Column("external_order_id", sa.String(length=128), nullable=True),
            )
        if "payment_url" not in columns:
            op.add_column(PAYMENTS_TABLE, sa.Column("payment_url", sa.Text(), nullable=True))
        if "idempotency_key" not in columns:
            op.add_column(
                PAYMENTS_TABLE,
                sa.Column("idempotency_key", sa.String(length=64), nullable=True),
            )

        _ensure_unique_constraint(
            bind,
            PAYMENTS_TABLE,
            PAYMENT_PROVIDER_ID_UNIQUE,
            ["payment_method", "payment_id"],
        )
        # On SQLite the constraint above recreates the table. Create indexes
        # afterwards so they cannot be lost during that copy operation.
        _ensure_unique_index(bind, PAYMENTS_TABLE, EXTERNAL_ORDER_INDEX, ["external_order_id"])
        _ensure_unique_index(bind, PAYMENTS_TABLE, IDEMPOTENCY_KEY_INDEX, ["idempotency_key"])

    if _has_table(bind, REFERRALS_TABLE):
        _ensure_unique_constraint(
            bind,
            REFERRALS_TABLE,
            REFERRAL_ORDER_UNIQUE,
            ["order_id", "referrer_id"],
        )

    if _has_table(bind, ACCOUNTS_TABLE):
        _ensure_index(bind, ACCOUNTS_TABLE, ACCOUNT_ORDER_INDEX, ["order_id"])


def downgrade() -> None:
    """Do not drop safety constraints or fields automatically.

    This bootstrap revision can be applied to databases that may already have
    some of these objects (from ``create_all``). Alembic cannot safely tell
    which objects predated the revision, so automatic downgrade could remove
    an existing protection or data. Restore a backup or create an explicit,
    reviewed rollback migration if a rollback is actually required.
    """
    raise NotImplementedError(
        "20260728_01 is forward-only to avoid deleting payment/referral data or "
        "pre-existing uniqueness protections."
    )
